### ISSUE TITLE
Why you just do not use Hydra Go SDK?

### ISSUE THREAD

**Issue by DenisNeustroev** [letsrock-today/authkit#1]
Official example of using hydra is using own http request because there isn't SDK for Node.js, but there is for Go. So you configuration and auth service could be much simpler.

**Comment by nikolay-turpitko** [comment]
Hi! Thank you for interest and feedback. This is not a production-ready project, we are learning and experimenting yet. Initially, we ported https://github.com/ory-am/hydra-idp-react to Go and RiotJS and then started from there to add functionality we need. We aware that we can use Go SDK, but decided to postpone this step till we finish some more difficult and important parts and be ready to polish our sample and extract some parts of it into kind of lib, which we hope to use in another our project. To be honest, right now we are more concerned whether we use OAuth2 and Hydra properly at all, especially in our SSO scenario and access token validation middleware. So, feel free to fork, experiment and send PR(s) if you wish, or just stay tuned, we hope to fix this issue later.

**Comment by nikolay-turpitko** [comment]
I've took another look at Hydra's Go SDK package. Right now it is a subpackage of the whole Hydra project residing in the same repository as a subfolder. Moreover, it depends on other packages from the same repo. We use glide to manage dependencies and I was not able to get only SDK package as a dependency, instead we'd have to depend on the whole Hydra project, which, in turn, required many other dependencies not really used in our project. Unless Hydra guys agreed to move SDK package into separate repository we'd rather not use it. See https://github.com/ory-am/hydra/issues/266.

**Comment by nikolay-turpitko** [comment]
With commit c356ab46cb1ebc5a00185d11c00ada0222cdd9c8 I've added generation of client's code for Hydra API from swagger spec. Probably, it didn't worth the trouble anyway. Just wanted to give it a try. We use only about 5 methods from Hydra API. I don't think we should introduce a huge dependency to the whole Hydra because of this 5 method calls.
