### ISSUE TITLE
Get user by access token in the middleware

### ISSUE THREAD

**Issue by austinov** [letsrock-today/authkit#14]
In the "accesstoken" middleware, the user is determined by an access token
which is kept in a store via UserService.UserByAccessToken.
But the store has only one access token per user and provider.
So when user will login from different devices or browsers
access tokens will be different and we will not be able to correctly identify the user.

In the middleware we should query a user by using the Hydra-API, but not via the UserService.
Or another way is to store the tokens for all user sessions

During logout user, we should revoke the access token which is associated with this user session
and not to affect others tokens of this user.

Related #10 .

**Comment by nikolay-turpitko** [comment]
Clarification: obtain "subject" by token via Hydra API, then user by "subject" == userID (login) from user service.
